/**
 * questions.js
 * NAPLAN Arena — Year 9 MCQ question bank (80 items)
 *
 * All questions are original and NAPLAN-style (not copied from official papers).
 * Each item includes tags for domain/category/strand/subskill and a calculator flag.
 */

const questionManifest = {
  "yearLevel": 9,
  "totalQuestions": 80,
  "countsByCategory": {
    "writing_skills": 8,
    "reading": 8,
    "spelling": 8,
    "grammar_punctuation": 8,
    "number_non_calculator": 8,
    "number_calculator_allowed": 8,
    "algebra_calculator_allowed": 8,
    "geometry_calculator_allowed": 8,
    "measurement_calculator_allowed": 8,
    "chance_data_calculator_allowed": 8
  },
  "difficultyCounts": {
    "3": 18,
    "4": 43,
    "5": 19
  },
  "calculatorCounts": {
    "n/a": 32,
    "not_allowed": 8,
    "allowed": 40
  },
  "domainCounts": {
    "writing": 8,
    "reading": 8,
    "conventions_of_language": 16,
    "numeracy": 48
  }
};

const questionBank = [
  {"id":"write-001","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"thesis_statement","calculator":"n/a","difficulty":3,"mode":"WRITING FORGE","type":"mcq","question":"Prompt: \"Year 9 students should complete community service as part of school.\"\\n\\nWhich thesis statement is strongest for a persuasive text?","answers":[{"text":"Community service is something that students can do.","correct":false},{"text":"Year 9 students should complete community service because it builds civic responsibility and practical skills.","correct":true},{"text":"Community service is important, and some people disagree with it.","correct":false},{"text":"Community service might be good, but it also might be bad.","correct":false}],"explanation":"A strong thesis clearly states a position and previews reasons the writer will develop."},
  {"id":"write-002","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"evidence_selection","calculator":"n/a","difficulty":4,"mode":"WRITING FORGE","type":"mcq","question":"Claim: \"Later school start times improve learning.\"\\n\\nWhich evidence best supports the claim?","answers":[{"text":"Some students say they do not like mornings.","correct":false},{"text":"A teacher prefers teaching later in the day.","correct":false},{"text":"A study comparing two similar schools found the later-start group had higher attendance and fewer first-period failures.","correct":true},{"text":"Many buses already run early routes.","correct":false}],"explanation":"Good evidence is specific, relevant, and directly linked to the claim (not just opinions)."},
  {"id":"write-003","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"counterargument_rebuttal","calculator":"n/a","difficulty":4,"mode":"WRITING FORGE","type":"mcq","question":"Topic: \"Phones should be kept out of classrooms.\"\\n\\nWhich sentence is the best rebuttal to this counterargument?\\n\\nCounterargument: \"Students need phones for emergencies.\"","answers":[{"text":"Phones are fun, and students like them.","correct":false},{"text":"Emergencies are rare, and schools already have office phones and approved contact systems for urgent situations.","correct":true},{"text":"Some students forget to charge their phones.","correct":false},{"text":"Teachers also use phones sometimes.","correct":false}],"explanation":"A rebuttal directly addresses the counterargument with a reason that reduces its strength."},
  {"id":"write-004","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"cohesion_transitions","calculator":"n/a","difficulty":3,"mode":"WRITING FORGE","type":"mcq","question":"Choose the best transition word or phrase:\\n\\n\"Public transport can reduce traffic near schools. ________, it can also lower air pollution in the neighborhood.\"","answers":[{"text":"However","correct":false},{"text":"In addition","correct":true},{"text":"For example","correct":false},{"text":"Meanwhile","correct":false}],"explanation":"\"In addition\" signals an extra supporting point that goes in the same direction."},
  {"id":"write-005","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"sentence_fluency_revision","calculator":"n/a","difficulty":5,"mode":"WRITING FORGE","type":"mcq","question":"Which revision best improves clarity and eliminates redundancy?\\n\\nOriginal: \"The reason why students should recycle is because it helps the environment.\"","answers":[{"text":"The reason why students should recycle is because it is good.","correct":false},{"text":"Students should recycle because it helps the environment.","correct":true},{"text":"Students should recycle, and the environment is helped by recycling.","correct":false},{"text":"Recycling is something students should do, which is because it helps.","correct":false}],"explanation":"The best revision removes extra wording but keeps the meaning."},
  {"id":"write-006","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"tone_modality","calculator":"n/a","difficulty":4,"mode":"WRITING FORGE","type":"mcq","question":"Which sentence uses the most persuasive modality (strongest level of certainty)?","answers":[{"text":"Schools could consider offering healthier canteen options.","correct":false},{"text":"Schools might want to offer healthier canteen options.","correct":false},{"text":"Schools should offer healthier canteen options to support student wellbeing.","correct":true},{"text":"Schools may offer healthier canteen options if they want.","correct":false}],"explanation":"Stronger modality uses words like \"should\" to express a clear recommendation."},
  {"id":"write-007","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"organising_arguments","calculator":"n/a","difficulty":4,"mode":"WRITING FORGE","type":"mcq","question":"Which sentence would be the most effective topic sentence for a body paragraph in an essay arguing for more school sport?","answers":[{"text":"Some people like sport and others do not.","correct":false},{"text":"School sport is a thing that happens every week.","correct":false},{"text":"Regular school sport improves students' physical health and reduces stress.","correct":true},{"text":"Sport has existed for many years in many countries.","correct":false}],"explanation":"A strong topic sentence clearly states a focused reason that supports the overall argument."},
  {"id":"write-008","yearLevel":9,"domain":"writing","category":"writing_skills","strand":"english","subskill":"concise_conclusion","calculator":"n/a","difficulty":3,"mode":"WRITING FORGE","type":"mcq","question":"Which concluding sentence best sums up an argument that social media use should be limited on school nights?","answers":[{"text":"In conclusion, social media is a popular thing that many students use.","correct":false},{"text":"Therefore, limiting social media on school nights will help students focus, sleep better, and arrive at school ready to learn.","correct":true},{"text":"This shows that social media is not always bad and can be fun sometimes.","correct":false},{"text":"Social media will probably keep changing into the future.","correct":false}],"explanation":"A good concluding sentence restates the position and key reasons in a concise way."},

  {"id":"read-001","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"inference_character_motivation","calculator":"n/a","difficulty":3,"mode":"READING BLITZ","type":"mcq","question":"Read the text:\\n\\nAri reread the email for the third time. The words were polite, but the short sentences felt heavy. He hovered over the reply button, deleted his first draft, and started again - slower this time.\\n\\nWhat can you infer about Ari?","answers":[{"text":"He is confident and rushing to respond quickly.","correct":false},{"text":"He is anxious about how his reply will be received.","correct":true},{"text":"He is confused because he cannot read the email.","correct":false},{"text":"He is excited because the email is very funny.","correct":false}],"explanation":"Deleting drafts and rereading suggests he is worried about making the right impression."},
  {"id":"read-002","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"author_technique_contrast","calculator":"n/a","difficulty":4,"mode":"READING BLITZ","type":"mcq","question":"Read the text:\\n\\nThe stadium was silent - until the final whistle cracked the air. Then the crowd erupted, a wave of sound rushing over the seats.\\n\\nWhat is the effect of the contrast in this description?","answers":[{"text":"It shows the writer does not know what happened.","correct":false},{"text":"It highlights how suddenly the atmosphere changed.","correct":true},{"text":"It proves the game lasted only a few seconds.","correct":false},{"text":"It suggests the crowd was bored the entire time.","correct":false}],"explanation":"The shift from \"silent\" to \"erupted\" emphasizes a sudden, dramatic change."},
  {"id":"read-003","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"main_idea_precision","calculator":"n/a","difficulty":4,"mode":"READING BLITZ","type":"mcq","question":"Read the text:\\n\\nReusable bags reduce waste, but they only work when used repeatedly. Buying a new \"reusable\" bag every shopping trip cancels the benefit. The goal is not to own more bags - it is to reuse the same one.\\n\\nWhich statement best expresses the main idea?","answers":[{"text":"Reusable bags are always better than plastic bags.","correct":false},{"text":"People should reuse the same bag many times to reduce waste.","correct":true},{"text":"Shopping trips should be avoided to protect the environment.","correct":false},{"text":"Plastic bags are cheaper than reusable bags.","correct":false}],"explanation":"The paragraph's focus is repeated reuse, not just purchasing reusable items."},
  {"id":"read-004","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"locating_information_multiple_steps","calculator":"n/a","difficulty":5,"mode":"READING BLITZ","type":"mcq","question":"Read the notice:\\n\\nLibrary Hours (Exam Week)\\nMon-Thu: 7:30 a.m.-5:00 p.m.\\nFri: 7:30 a.m.-3:30 p.m.\\nClosed Saturday\\nSunday: 12:00 p.m.-4:00 p.m.\\n\\nJordan wants to study for 3 hours in the library on the weekend. Which option is possible?","answers":[{"text":"Saturday, 10:00 a.m.-1:00 p.m.","correct":false},{"text":"Sunday, 11:00 a.m.-2:00 p.m.","correct":false},{"text":"Sunday, 1:00 p.m.-4:00 p.m.","correct":true},{"text":"Friday, 4:00 p.m.-7:00 p.m.","correct":false}],"explanation":"The library is closed Saturday, and Sunday is open 12:00-4:00, so 1:00-4:00 works."},
  {"id":"read-005","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"compare_viewpoints","calculator":"n/a","difficulty":4,"mode":"READING BLITZ","type":"mcq","question":"Read the two opinions:\\n\\nOpinion A: \"Homework should be shorter because students need time for sleep, exercise, and family.\"\\nOpinion B: \"Homework should be purposeful; busywork wastes time and does not improve learning.\"\\n\\nWhich statement is supported by BOTH opinions?","answers":[{"text":"Homework should be banned completely.","correct":false},{"text":"Homework is useful only when it has a clear learning purpose.","correct":true},{"text":"Students should spend at least two hours on homework every night.","correct":false},{"text":"Teachers should never check homework.","correct":false}],"explanation":"Both focus on avoiding wasted time and keeping homework useful (not just longer)."},
  {"id":"read-006","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"evaluate_argument_strengthen","calculator":"n/a","difficulty":5,"mode":"READING BLITZ","type":"mcq","question":"An article argues: \"Schools should plant more trees because trees make school environments healthier.\"\\n\\nWhich additional information would MOST strengthen the argument?","answers":[{"text":"Some students like taking photos of trees.","correct":false},{"text":"A local nursery sells many types of trees.","correct":false},{"text":"A study found that schools with more shade trees had lower playground temperatures and fewer heat-related sick-bay visits.","correct":true},{"text":"Trees can be green or brown depending on the season.","correct":false}],"explanation":"Strong support links trees to measurable health-related improvements in a school context."},
  {"id":"read-007","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"tone_attitude","calculator":"n/a","difficulty":4,"mode":"READING BLITZ","type":"mcq","question":"Read the sentence:\\n\\n\"The new timetable was announced with great enthusiasm, but the groans from the back row were impossible to miss.\"\\n\\nWhat is the writer's attitude towards the new timetable?","answers":[{"text":"Completely supportive","correct":false},{"text":"Amused by the mixed reactions","correct":true},{"text":"Angry about the change","correct":false},{"text":"Unaware that students dislike it","correct":false}],"explanation":"The contrast between \"enthusiasm\" and \"groans\" suggests a slightly amused view of the situation."},
  {"id":"read-008","yearLevel":9,"domain":"reading","category":"reading","strand":"english_literacy","subskill":"purpose_audience","calculator":"n/a","difficulty":3,"mode":"READING BLITZ","type":"mcq","question":"A school newsletter article begins: \"Next term, our school will trial a walking school bus to make morning drop-off safer and less congested.\"\\n\\nWhat is the main purpose of this sentence?","answers":[{"text":"To entertain readers with a funny story","correct":false},{"text":"To persuade families to stop driving altogether","correct":false},{"text":"To inform the school community about a new safety initiative","correct":true},{"text":"To criticize parents who arrive late","correct":false}],"explanation":"The sentence introduces a new program and explains its purpose to the school community."},

  {"id":"spell-001","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"double_consonant_pattern","calculator":"n/a","difficulty":4,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling to replace the incorrect word:\\n\\n\"The hotel could not accomodate the extra guests.\"","answers":[{"text":"accommodate","correct":true},{"text":"accomodate","correct":false},{"text":"acommodate","correct":false},{"text":"accommadate","correct":false}],"explanation":"The correct spelling is \"accommodate\" (double c and double m)."},
  {"id":"spell-002","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"vowel_pattern","calculator":"n/a","difficulty":3,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling:\\n\\n\"Please respond to the email immediatly.\"","answers":[{"text":"immediately","correct":true},{"text":"immediatly","correct":false},{"text":"immedietly","correct":false},{"text":"immediatelly","correct":false}],"explanation":"The correct spelling is \"immediately.\""},
  {"id":"spell-003","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"common_confusion","calculator":"n/a","difficulty":3,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling:\\n\\n\"Keep your work in a seperate folder.\"","answers":[{"text":"separate","correct":true},{"text":"seperate","correct":false},{"text":"seperete","correct":false},{"text":"sepparate","correct":false}],"explanation":"The correct spelling is \"separate.\""},
  {"id":"spell-004","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"suffix_tion_sion","calculator":"n/a","difficulty":5,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling:\\n\\n\"The scientist published her conclusion in a journal.\"","answers":[{"text":"conclusion","correct":true},{"text":"conclution","correct":false},{"text":"conclusian","correct":false},{"text":"conclussion","correct":false}],"explanation":"The correct spelling is \"conclusion\" (an -sion ending)."},
  {"id":"spell-005","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"silent_letters","calculator":"n/a","difficulty":4,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling:\\n\\n\"The rhythm of the song was easy to follow.\"","answers":[{"text":"rhythm","correct":true},{"text":"rythm","correct":false},{"text":"rithym","correct":false},{"text":"rhythym","correct":false}],"explanation":"The correct spelling is \"rhythm.\""},
  {"id":"spell-006","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"word_endings","calculator":"n/a","difficulty":4,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling:\\n\\n\"Regular maintenence prevents equipment failure.\"","answers":[{"text":"maintenance","correct":true},{"text":"maintenence","correct":false},{"text":"maintainence","correct":false},{"text":"maintainance","correct":false}],"explanation":"The correct spelling is \"maintenance.\""},
  {"id":"spell-007","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"prefix_suffix","calculator":"n/a","difficulty":3,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correct spelling:\\n\\n\"The instructions were unusually complicated.\"","answers":[{"text":"unusually","correct":true},{"text":"unussually","correct":false},{"text":"unnusually","correct":false},{"text":"unusalley","correct":false}],"explanation":"The correct spelling is \"unusually.\""},
  {"id":"spell-008","yearLevel":9,"domain":"conventions_of_language","category":"spelling","strand":"spelling","subskill":"common_error_ie_ei","calculator":"n/a","difficulty":4,"mode":"SPELLING STRIKE","type":"mcq","question":"Choose the correctly spelled word to complete the sentence:\\n\\n\"The committee will review the safety ____ next week.\"","answers":[{"text":"procedure","correct":true},{"text":"proceedure","correct":false},{"text":"procedur","correct":false},{"text":"prochedure","correct":false}],"explanation":"The correct spelling is \"procedure.\""},

  {"id":"gram-001","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"grammar","subskill":"subject_verb_agreement","calculator":"n/a","difficulty":3,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which option correctly completes the sentence?\\n\\n\"Neither the coach nor the players ___ ready to leave.\"","answers":[{"text":"was","correct":false},{"text":"were","correct":true},{"text":"is","correct":false},{"text":"be","correct":false}],"explanation":"With \"neither...nor,\" the verb agrees with the closest subject (\"players\" = plural), so \"were\" is correct."},
  {"id":"gram-002","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"grammar","subskill":"pronoun_case","calculator":"n/a","difficulty":4,"mode":"GRAMMAR GUARD","type":"mcq","question":"Choose the correct option:\\n\\n\"The teacher spoke to Sam and ___ after class.\"","answers":[{"text":"I","correct":false},{"text":"me","correct":true},{"text":"myself","correct":false},{"text":"mine","correct":false}],"explanation":"After the preposition \"to,\" use the object pronoun: \"me.\""},
  {"id":"gram-003","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"punctuation","subskill":"comma_splice_semicolon","calculator":"n/a","difficulty":5,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which sentence uses punctuation correctly?","answers":[{"text":"The storm intensified, the game continued.","correct":false},{"text":"The storm intensified; the game continued.","correct":true},{"text":"The storm intensified; and the game continued.","correct":false},{"text":"The storm intensified, and; the game continued.","correct":false}],"explanation":"A semicolon correctly joins two closely related independent clauses without a conjunction."},
  {"id":"gram-004","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"grammar","subskill":"parallel_structure","calculator":"n/a","difficulty":4,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which option has correct parallel structure?","answers":[{"text":"The job requires planning carefully, to communicate clearly, and you must work as a team.","correct":false},{"text":"The job requires planning carefully, communicating clearly, and working as a team.","correct":true},{"text":"The job requires to plan carefully, communicating clearly, and to work as a team.","correct":false},{"text":"The job requires planning carefully, communicate clearly, and working as a team.","correct":false}],"explanation":"Items in a list should share the same grammatical form (all -ing phrases here)."},
  {"id":"gram-005","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"punctuation","subskill":"apostrophes_plural_possession","calculator":"n/a","difficulty":4,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which option correctly shows plural possession?\\n\\nThe lockers belonging to the students","answers":[{"text":"the student's lockers","correct":false},{"text":"the students' lockers","correct":true},{"text":"the students lockers","correct":false},{"text":"the students's lockers","correct":false}],"explanation":"For plural possession ending in s, place the apostrophe after the s: students'."},
  {"id":"gram-006","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"punctuation","subskill":"nonessential_clause_commas","calculator":"n/a","difficulty":5,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which sentence punctuates the nonessential clause correctly?","answers":[{"text":"Jordan who lives in Denver is visiting next week.","correct":false},{"text":"Jordan, who lives in Denver, is visiting next week.","correct":true},{"text":"Jordan who lives, in Denver is visiting next week.","correct":false},{"text":"Jordan, who lives in Denver is visiting, next week.","correct":false}],"explanation":"Nonessential information is set off with commas: 'Jordan, who lives in Denver, ...'."},
  {"id":"gram-007","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"grammar","subskill":"verb_tense_consistency","calculator":"n/a","difficulty":3,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which sentence uses verb tenses consistently?","answers":[{"text":"Yesterday we walk to the park and played basketball.","correct":false},{"text":"Yesterday we walked to the park and play basketball.","correct":false},{"text":"Yesterday we walked to the park and played basketball.","correct":true},{"text":"Yesterday we are walking to the park and played basketball.","correct":false}],"explanation":"Both verbs should be in the past tense: 'walked' and 'played.'"},
  {"id":"gram-008","yearLevel":9,"domain":"conventions_of_language","category":"grammar_punctuation","strand":"punctuation","subskill":"colon_introduction","calculator":"n/a","difficulty":4,"mode":"GRAMMAR GUARD","type":"mcq","question":"Which sentence uses a colon correctly?","answers":[{"text":"The coach gave us three instructions: warm up properly, play fairly, and support each other.","correct":true},{"text":"The coach: gave us three instructions, warm up properly, play fairly, and support each other.","correct":false},{"text":"The coach gave us: three instructions, warm up properly, play fairly, and support each other.","correct":false},{"text":"The coach gave us three: instructions warm up properly, play fairly, and support each other.","correct":false}],"explanation":"A colon can introduce a list after a complete main clause."},

  {"id":"num-nc-001","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"percent_of_quantity","calculator":"not_allowed","difficulty":3,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"What is 12.5% of 96?","answers":[{"text":"10","correct":false},{"text":"12","correct":true},{"text":"14","correct":false},{"text":"18","correct":false}],"explanation":"12.5% is 1/8, and 96 ÷ 8 = 12."},
  {"id":"num-nc-002","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"index_laws","calculator":"not_allowed","difficulty":4,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"Simplify: (2^5 * 2^3) ÷ 2^4","answers":[{"text":"2^4","correct":true},{"text":"2^6","correct":false},{"text":"2^8","correct":false},{"text":"2^12","correct":false}],"explanation":"Add exponents when multiplying and subtract when dividing: 2^(5+3-4) = 2^4."},
  {"id":"num-nc-003","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"ratio_proportion","calculator":"not_allowed","difficulty":4,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"A recipe uses a flour:sugar ratio of 5:2. If you use 350 g of flour, how much sugar is needed?","answers":[{"text":"70 g","correct":false},{"text":"140 g","correct":true},{"text":"175 g","correct":false},{"text":"280 g","correct":false}],"explanation":"350 g represents 5 parts, so 1 part is 70 g. Sugar is 2 parts: 2 * 70 = 140 g."},
  {"id":"num-nc-004","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"fraction_to_percentage","calculator":"not_allowed","difficulty":5,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"Which percentage is equal to 7/16?","answers":[{"text":"37.5%","correct":false},{"text":"43.75%","correct":true},{"text":"56.25%","correct":false},{"text":"62.5%","correct":false}],"explanation":"1/16 = 6.25%, so 7/16 = 7 * 6.25% = 43.75%."},
  {"id":"num-nc-005","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"successive_percentage_change","calculator":"not_allowed","difficulty":5,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"A price is reduced by 20%, then increased by 20% of the reduced price. Compared to the original price, the final price is:","answers":[{"text":"4% less","correct":true},{"text":"the same","correct":false},{"text":"4% more","correct":false},{"text":"20% less","correct":false}],"explanation":"Multiply the multipliers: 0.8 * 1.2 = 0.96, so the final price is 96% of the original (4% less)."},
  {"id":"num-nc-006","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"compare_representations","calculator":"not_allowed","difficulty":4,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"Which value is greatest?","answers":[{"text":"5/8","correct":false},{"text":"0.625","correct":false},{"text":"62.5%","correct":false},{"text":"0.63","correct":true}],"explanation":"5/8, 0.625, and 62.5% are equal; 0.63 is slightly larger."},
  {"id":"num-nc-007","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"integers_order","calculator":"not_allowed","difficulty":3,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"Which list orders the numbers from smallest to largest?\\n\\n-3, 2, -5, 0","answers":[{"text":"2, 0, -3, -5","correct":false},{"text":"-5, -3, 0, 2","correct":true},{"text":"-3, -5, 0, 2","correct":false},{"text":"-5, 0, -3, 2","correct":false}],"explanation":"On the number line, -5 is least, then -3, then 0, then 2."},
  {"id":"num-nc-008","yearLevel":9,"domain":"numeracy","category":"number_non_calculator","strand":"number","subskill":"algebraic_evaluation_no_calc","calculator":"not_allowed","difficulty":4,"mode":"NUMBER RUSH (NO CALC)","type":"mcq","question":"Evaluate 3a^2 - 2a when a = -2.","answers":[{"text":"8","correct":false},{"text":"16","correct":true},{"text":"20","correct":false},{"text":"-16","correct":false}],"explanation":"3(-2)^2 - 2(-2) = 3 * 4 + 4 = 12 + 4 = 16."},

  {"id":"num-ca-001","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"reverse_percentages","calculator":"allowed","difficulty":4,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"After a 15% discount, a jacket costs $68.00. What was the original price?","answers":[{"text":"$57.80","correct":false},{"text":"$78.20","correct":false},{"text":"$80.00","correct":true},{"text":"$92.00","correct":false}],"explanation":"Discounted price = 0.85 * original, so original = 68 ÷ 0.85 = 80."},
  {"id":"num-ca-002","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"compound_interest","calculator":"allowed","difficulty":5,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"You invest $1,200 at 3.5% interest compounded annually for 2 years. What is the final amount (nearest cent)?","answers":[{"text":"$1,242.00","correct":false},{"text":"$1,285.47","correct":true},{"text":"$1,287.00","correct":false},{"text":"$1,296.00","correct":false}],"explanation":"A = 1200 * 1.035^2 ≈ 1285.47."},
  {"id":"num-ca-003","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"average_rate","calculator":"allowed","difficulty":4,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"A car travels 450 km in 5.5 hours. What is the average speed (km/h) to the nearest tenth?","answers":[{"text":"72.8","correct":false},{"text":"81.8","correct":true},{"text":"83.3","correct":false},{"text":"90.0","correct":false}],"explanation":"Speed = distance ÷ time = 450 ÷ 5.5 ≈ 81.8 km/h."},
  {"id":"num-ca-004","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"percent_addition_tax","calculator":"allowed","difficulty":3,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"A device costs $249.90 before tax. If a 10% tax is added, what is the total cost (nearest cent)?","answers":[{"text":"$259.90","correct":false},{"text":"$274.89","correct":true},{"text":"$274.90","correct":false},{"text":"$299.88","correct":false}],"explanation":"Total = 249.90 * 1.10 = 274.89 (to the nearest cent)."},
  {"id":"num-ca-005","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"exponential_growth","calculator":"allowed","difficulty":5,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"A population of 18,500 grows by 2.2% each year. What is the population after 4 years (nearest whole number)?","answers":[{"text":"19,628","correct":false},{"text":"20,183","correct":true},{"text":"20,948","correct":false},{"text":"21,725","correct":false}],"explanation":"Population = 18,500 * 1.022^4 ≈ 20,182.5, which rounds to 20,183."},
  {"id":"num-ca-006","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"percent_mass","calculator":"allowed","difficulty":3,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"A solution is 18% salt by mass. How many grams of salt are in 2.75 kg of solution?","answers":[{"text":"450 g","correct":false},{"text":"495 g","correct":true},{"text":"525 g","correct":false},{"text":"540 g","correct":false}],"explanation":"2.75 kg = 2750 g; 18% of 2750 is 0.18 * 2750 = 495 g."},
  {"id":"num-ca-007","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"percent_discount_multiple_items","calculator":"allowed","difficulty":4,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"A cafe sells smoothies for $6.75 each. If you buy 3 smoothies, you get 15% off the total. What is the final cost (nearest cent)?","answers":[{"text":"$17.01","correct":false},{"text":"$17.21","correct":true},{"text":"$17.31","correct":false},{"text":"$18.21","correct":false}],"explanation":"Total before discount: 3 * 6.75 = 20.25. After 15% off: 20.25 * 0.85 = 17.2125, which rounds to $17.21."},
  {"id":"num-ca-008","yearLevel":9,"domain":"numeracy","category":"number_calculator_allowed","strand":"number","subskill":"deposit_and_installments","calculator":"allowed","difficulty":4,"mode":"NUMBER RUSH (CALC)","type":"mcq","question":"A laptop costs $1,499. A deposit of 12% is paid, then the remaining balance is paid in 6 equal monthly payments. What is each monthly payment (nearest cent)?","answers":[{"text":"$199.88","correct":false},{"text":"$219.85","correct":true},{"text":"$224.85","correct":false},{"text":"$239.85","correct":false}],"explanation":"Deposit = 0.12 * 1499 = 179.88. Remaining = 1499 - 179.88 = 1319.12. Monthly payment = 1319.12 ÷ 6 ≈ 219.85."},

  {"id":"alg-ca-001","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"solve_linear_equation_decimals","calculator":"allowed","difficulty":4,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Solve for x: 0.4(5x - 3) = 2.6","answers":[{"text":"x = 1.2","correct":false},{"text":"x = 1.9","correct":true},{"text":"x = 2.4","correct":false},{"text":"x = 3.8","correct":false}],"explanation":"0.4(5x-3) = 2x - 1.2. So 2x - 1.2 = 2.6 -> 2x = 3.8 -> x = 1.9."},
  {"id":"alg-ca-002","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"simultaneous_equations","calculator":"allowed","difficulty":4,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Solve the system: 2x + y = 11 and x - y = 1","answers":[{"text":"x = 3, y = 5","correct":false},{"text":"x = 4, y = 3","correct":true},{"text":"x = 5, y = 1","correct":false},{"text":"x = 6, y = -1","correct":false}],"explanation":"Add the equations to eliminate y: 3x = 12 -> x = 4. Substitute: 2(4) + y = 11 -> y = 3."},
  {"id":"alg-ca-003","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"solve_quadratic_factor","calculator":"allowed","difficulty":4,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Solve: x^2 - 6x - 7 = 0","answers":[{"text":"x = 7 or x = -1","correct":true},{"text":"x = 1 or x = -7","correct":false},{"text":"x = 6 or x = -7","correct":false},{"text":"x = -6 or x = 7","correct":false}],"explanation":"Factor: (x - 7)(x + 1) = 0, so x = 7 or x = -1."},
  {"id":"alg-ca-004","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"substitution","calculator":"allowed","difficulty":3,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Evaluate g(x) = x^2 + 2x when x = -3","answers":[{"text":"-15","correct":false},{"text":"-3","correct":false},{"text":"3","correct":true},{"text":"15","correct":false}],"explanation":"g(-3) = (-3)^2 + 2(-3) = 9 - 6 = 3."},
  {"id":"alg-ca-005","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"rearrange_formula","calculator":"allowed","difficulty":5,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Rearrange P = 2(l + w) + 3h to make h the subject.","answers":[{"text":"h = (P - 2(l + w)) / 3","correct":true},{"text":"h = (P + 2(l + w)) / 3","correct":false},{"text":"h = P - 2(l + w) - 3","correct":false},{"text":"h = 3(P - 2(l + w))","correct":false}],"explanation":"Subtract 2(l+w) from both sides, then divide by 3."},
  {"id":"alg-ca-006","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"solve_rational_equation","calculator":"allowed","difficulty":5,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Solve for x: (x + 3) / (x - 1) = 2.5  (x \u2260 1)","answers":[{"text":"x = 11/3","correct":true},{"text":"x = 3/11","correct":false},{"text":"x = 5/2","correct":false},{"text":"x = 7/2","correct":false}],"explanation":"x + 3 = 2.5(x - 1) = 2.5x - 2.5. So 5.5 = 1.5x -> x = 11/3."},
  {"id":"alg-ca-007","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"equation_of_line_two_points","calculator":"allowed","difficulty":4,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"A line passes through points (2, 5) and (6, 1). Which equation describes the line?","answers":[{"text":"y = x + 3","correct":false},{"text":"y = -x + 7","correct":true},{"text":"y = -x - 7","correct":false},{"text":"y = x - 7","correct":false}],"explanation":"Slope m = (1-5)/(6-2) = -4/4 = -1. Using (2,5): 5 = -2 + b -> b = 7."},
  {"id":"alg-ca-008","yearLevel":9,"domain":"numeracy","category":"algebra_calculator_allowed","strand":"algebra","subskill":"solve_simple_rational","calculator":"allowed","difficulty":4,"mode":"ALGEBRA ARENA (CALC)","type":"mcq","question":"Solve for x: 5 / (x + 1) = 0.8","answers":[{"text":"x = 4.25","correct":false},{"text":"x = 5.25","correct":true},{"text":"x = 6.25","correct":false},{"text":"x = 7.25","correct":false}],"explanation":"x + 1 = 5 / 0.8 = 6.25, so x = 5.25."},

  {"id":"geo-ca-001","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"pythagoras_non_integer","calculator":"allowed","difficulty":4,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"A right triangle has legs 7.5 cm and 12.0 cm. What is the hypotenuse (nearest tenth)?","answers":[{"text":"13.5 cm","correct":false},{"text":"14.2 cm","correct":true},{"text":"15.0 cm","correct":false},{"text":"19.5 cm","correct":false}],"explanation":"Use Pythagoras: hypotenuse = sqrt(7.5^2 + 12^2) = sqrt(200.25) \u2248 14.2 cm."},
  {"id":"geo-ca-002","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"trigonometry_angle_of_elevation","calculator":"allowed","difficulty":5,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"A tree is 18 m tall. From a point 24 m away on level ground, what is the angle of elevation to the top (nearest tenth of a degree)?","answers":[{"text":"30.0 degrees","correct":false},{"text":"36.9 degrees","correct":true},{"text":"40.6 degrees","correct":false},{"text":"53.1 degrees","correct":false}],"explanation":"tan(theta) = 18/24 = 0.75, so theta = arctan(0.75) \u2248 36.9 degrees."},
  {"id":"geo-ca-003","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"arc_length","calculator":"allowed","difficulty":4,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"A circle has radius 8 cm. What is the length of an arc with a central angle of 135 degrees (nearest tenth)? Use pi on your calculator.","answers":[{"text":"9.4 cm","correct":false},{"text":"12.6 cm","correct":false},{"text":"18.8 cm","correct":true},{"text":"25.1 cm","correct":false}],"explanation":"Arc length = (135/360) * 2*pi*r = 0.375 * 16*pi = 6*pi \u2248 18.8 cm."},
  {"id":"geo-ca-004","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"bearings","calculator":"allowed","difficulty":4,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"A drone flies 10 km due east, then 10 km due north. What is the bearing of the final position from the start?","answers":[{"text":"045 degrees","correct":true},{"text":"090 degrees","correct":false},{"text":"135 degrees","correct":false},{"text":"315 degrees","correct":false}],"explanation":"The displacement is northeast (equal east and north), so the bearing from north is 045 degrees."},
  {"id":"geo-ca-005","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"similarity_area_scale_factor","calculator":"allowed","difficulty":4,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"Two shapes are similar. The scale factor from Shape A to Shape B is 1.5. If the area of Shape A is 32 cm^2, what is the area of Shape B?","answers":[{"text":"48 cm^2","correct":false},{"text":"64 cm^2","correct":false},{"text":"72 cm^2","correct":true},{"text":"96 cm^2","correct":false}],"explanation":"Area scale factor = 1.5^2 = 2.25. So 32 * 2.25 = 72 cm^2."},
  {"id":"geo-ca-006","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"midpoint","calculator":"allowed","difficulty":3,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"What is the midpoint of the line segment joining (-4, 7) and (10, -1)?","answers":[{"text":"(3, 3)","correct":true},{"text":"(6, 6)","correct":false},{"text":"(-7, 9)","correct":false},{"text":"(14, -8)","correct":false}],"explanation":"Midpoint is the average of coordinates: ((-4+10)/2, (7+(-1))/2) = (3, 3)."},
  {"id":"geo-ca-007","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"pythagoras_ladder","calculator":"allowed","difficulty":4,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"A ladder is 5.6 m long and its base is 1.8 m from a wall. How high up the wall does the ladder reach (nearest tenth)?","answers":[{"text":"4.8 m","correct":false},{"text":"5.3 m","correct":true},{"text":"5.6 m","correct":false},{"text":"7.4 m","correct":false}],"explanation":"Height = sqrt(5.6^2 - 1.8^2) = sqrt(31.36 - 3.24) = sqrt(28.12) \u2248 5.3 m."},
  {"id":"geo-ca-008","yearLevel":9,"domain":"numeracy","category":"geometry_calculator_allowed","strand":"space","subskill":"interior_angle_polygon","calculator":"allowed","difficulty":5,"mode":"GEOMETRY GAUNTLET (CALC)","type":"mcq","question":"A regular polygon has interior angles of 150 degrees. How many sides does it have?","answers":[{"text":"10","correct":false},{"text":"12","correct":true},{"text":"14","correct":false},{"text":"15","correct":false}],"explanation":"Set (n-2)*180/n = 150. Then 180n - 360 = 150n -> 30n = 360 -> n = 12."},

  {"id":"meas-ca-001","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"surface_area_cylinder","calculator":"allowed","difficulty":5,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A closed cylinder has radius 5 cm and height 11 cm. What is the total surface area (nearest tenth)? Use pi on your calculator.","answers":[{"text":"314.2 cm^2","correct":false},{"text":"471.2 cm^2","correct":false},{"text":"502.7 cm^2","correct":true},{"text":"628.3 cm^2","correct":false}],"explanation":"Surface area = 2*pi*r(h + r) = 2*pi*5*(11 + 5) = 160*pi \u2248 502.7 cm^2."},
  {"id":"meas-ca-002","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"volume_cone","calculator":"allowed","difficulty":5,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A cone has radius 6 cm and height 10 cm. What is its volume (nearest whole cm^3)? Use pi on your calculator.","answers":[{"text":"188 cm^3","correct":false},{"text":"252 cm^3","correct":false},{"text":"377 cm^3","correct":true},{"text":"565 cm^3","correct":false}],"explanation":"Volume = (1/3)*pi*r^2*h = (1/3)*pi*36*10 = 120*pi \u2248 377 cm^3."},
  {"id":"meas-ca-003","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"scale_distance","calculator":"allowed","difficulty":3,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A map scale is 1:50,000. Two towns are 7.2 cm apart on the map. What is the actual distance (km)?","answers":[{"text":"0.36 km","correct":false},{"text":"3.6 km","correct":true},{"text":"36 km","correct":false},{"text":"360 km","correct":false}],"explanation":"7.2 cm * 50,000 = 360,000 cm = 3,600 m = 3.6 km."},
  {"id":"meas-ca-004","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"speed_unit_conversion","calculator":"allowed","difficulty":4,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"Convert 95 km/h to m/s (nearest tenth).","answers":[{"text":"19.0 m/s","correct":false},{"text":"24.6 m/s","correct":false},{"text":"26.4 m/s","correct":true},{"text":"34.2 m/s","correct":false}],"explanation":"Divide by 3.6: 95 \u00f7 3.6 \u2248 26.4 m/s."},
  {"id":"meas-ca-005","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"perimeter_composite_shape","calculator":"allowed","difficulty":4,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A rectangle is 8 m by 5 m. A semicircle with diameter 5 m is attached along one 5 m side (replacing that side). What is the perimeter (nearest tenth)? Use pi on your calculator.","answers":[{"text":"21.0 m","correct":false},{"text":"24.6 m","correct":false},{"text":"28.9 m","correct":true},{"text":"31.6 m","correct":false}],"explanation":"Perimeter = 8 + 8 + 5 + (pi * 2.5) \u2248 21 + 7.854 = 28.9 m."},
  {"id":"meas-ca-006","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"volume_unit_conversion_liters","calculator":"allowed","difficulty":4,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A tank is 1.2 m long, 0.8 m wide, and 0.75 m deep. It is filled to 2/3 of its height. How many liters of water are in the tank? (1 m^3 = 1000 L)","answers":[{"text":"320 L","correct":false},{"text":"480 L","correct":true},{"text":"720 L","correct":false},{"text":"960 L","correct":false}],"explanation":"Full volume = 1.2 * 0.8 * 0.75 = 0.72 m^3. Two-thirds is 0.48 m^3 = 480 L."},
  {"id":"meas-ca-007","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"fuel_consumption","calculator":"allowed","difficulty":4,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A car uses 7.8 liters of fuel per 100 km. Approximately how many liters are used to travel 415 km (nearest tenth)?","answers":[{"text":"29.9 L","correct":false},{"text":"32.4 L","correct":true},{"text":"34.0 L","correct":false},{"text":"40.2 L","correct":false}],"explanation":"Fuel used = 7.8 * (415/100) = 7.8 * 4.15 = 32.37, which rounds to 32.4 L."},
  {"id":"meas-ca-008","yearLevel":9,"domain":"numeracy","category":"measurement_calculator_allowed","strand":"measurement","subskill":"time_from_speed","calculator":"allowed","difficulty":4,"mode":"MEASUREMENT MISSION (CALC)","type":"mcq","question":"A cyclist travels 27.5 km at an average speed of 16.2 km/h. How long does the trip take (nearest whole minute)?","answers":[{"text":"92 minutes","correct":false},{"text":"102 minutes","correct":true},{"text":"112 minutes","correct":false},{"text":"117 minutes","correct":false}],"explanation":"Time = 27.5 \u00f7 16.2 \u2248 1.6975 hours. In minutes: 1.6975 * 60 \u2248 101.9, which rounds to 102 minutes."},

  {"id":"data-ca-001","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"probability","subskill":"conditional_probability","calculator":"allowed","difficulty":4,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"Survey results:\\n- 50 students play a sport\\n- Of those 50, 18 also have a part-time job\\n\\nWhat is P(job | plays sport)?","answers":[{"text":"18/80","correct":false},{"text":"18/50","correct":true},{"text":"32/50","correct":false},{"text":"50/18","correct":false}],"explanation":"Conditional probability uses the group after the bar: 18 out of 50 = 18/50 = 0.36."},
  {"id":"data-ca-002","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"probability","subskill":"without_replacement","calculator":"allowed","difficulty":5,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"A bag contains 4 red, 3 blue, and 5 green marbles (12 total). Two marbles are drawn without replacement. What is the probability both are blue?","answers":[{"text":"1/22","correct":true},{"text":"1/16","correct":false},{"text":"3/44","correct":false},{"text":"1/11","correct":false}],"explanation":"P(blue then blue) = (3/12) * (2/11) = 6/132 = 1/22."},
  {"id":"data-ca-003","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"probability","subskill":"expected_value","calculator":"allowed","difficulty":4,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"A game costs $0 to play.\\n- Win $6 with probability 1/4\\n- Win $2 with probability 1/2\\n- Lose $4 with probability 1/4\\n\\nWhat is the expected value (average gain) per game?","answers":[{"text":"$0.50","correct":false},{"text":"$1.00","correct":false},{"text":"$1.50","correct":true},{"text":"$2.00","correct":false}],"explanation":"EV = 0.25*6 + 0.5*2 + 0.25*(-4) = 1.5 + 1 - 1 = 1.5."},
  {"id":"data-ca-004","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"statistics","subskill":"mean_from_grouped_data","calculator":"allowed","difficulty":4,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"Minutes spent reading last night (grouped):\\n0-10: 4 students\\n10-20: 6 students\\n20-30: 10 students\\n\\nEstimate the mean reading time (minutes) using class midpoints.","answers":[{"text":"15","correct":false},{"text":"18","correct":true},{"text":"20","correct":false},{"text":"22","correct":false}],"explanation":"Use midpoints 5, 15, 25: mean \u2248 (4*5 + 6*15 + 10*25) / 20 = 360/20 = 18."},
  {"id":"data-ca-005","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"statistics","subskill":"interquartile_range","calculator":"allowed","difficulty":3,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"A box plot has Q1 = 10 and Q3 = 20.\\n\\nWhat is the interquartile range (IQR)?","answers":[{"text":"10","correct":true},{"text":"15","correct":false},{"text":"20","correct":false},{"text":"30","correct":false}],"explanation":"IQR = Q3 - Q1 = 20 - 10 = 10."},
  {"id":"data-ca-006","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"statistics","subskill":"variability_outliers","calculator":"allowed","difficulty":5,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"Two classes have these quiz scores:\\nClass A: 10, 10, 10, 10, 30\\nClass B: 14, 14, 14, 14, 14\\n\\nWhich statement is correct?","answers":[{"text":"Class A has the greater mean score.","correct":false},{"text":"Class B has the greater mean score.","correct":false},{"text":"Both classes have the same mean, but Class A has greater variability.","correct":true},{"text":"Both classes have the same range.","correct":false}],"explanation":"Both means are 14, but Class A's scores are spread out because of the 30 outlier."},
  {"id":"data-ca-007","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"probability","subskill":"complement_rule","calculator":"allowed","difficulty":5,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"A fair die is rolled three times. What is the probability of getting at least one 6? (Round to 3 decimal places.)","answers":[{"text":"0.216","correct":false},{"text":"0.375","correct":false},{"text":"0.421","correct":true},{"text":"0.579","correct":false}],"explanation":"Use the complement: 1 - (5/6)^3 = 1 - 125/216 = 91/216 \u2248 0.421."},
  {"id":"data-ca-008","yearLevel":9,"domain":"numeracy","category":"chance_data_calculator_allowed","strand":"probability","subskill":"union_of_events","calculator":"allowed","difficulty":4,"mode":"DATA & CHANCE (CALC)","type":"mcq","question":"In a year group, 40% of students play an instrument, 25% play a sport, and 10% do both. What percent play an instrument OR a sport?","answers":[{"text":"45%","correct":false},{"text":"55%","correct":true},{"text":"65%","correct":false},{"text":"75%","correct":false}],"explanation":"P(A or B) = P(A) + P(B) - P(A and B) = 40% + 25% - 10% = 55%."}
];

if (typeof window !== "undefined") {
  window.questionManifest = questionManifest;
  window.questionBank = questionBank;
}
